branch-defaults:
  master:
    environment: zensite-dev
    group_suffix: null
global:
  application_name: zensite
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 1.12.6
  default_region: us-east-1
  profile: null
  repository: null
  sc: null
