# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: nicholefrey/node-boron-elastic-beanstalk:1.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install
      # run tests!
      - run: yarn test
      - run: npm run lint
  deploy-job:
      <<: *defaults
      steps:
        - checkout
        - run:
            name: Deploy if tests pass and branch is Master
            command: |
              eb deploy --profile default

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-job:
          requires:
            - build
          filters:
            branches:
              only: master
