# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: nicholefrey/node-boron-elastic-beanstalk:1.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn install
      # run tests!
      - run: yarn test
      - run: npm run lint
  deploy-job:
      docker:
        - image: nicholefrey/node-boron-elastic-beanstalk:1.0
      working_directory: ~/repo
      steps:
        - run:
            name: Deploy if tests pass and branch is Master
            command: |
              eb init --debug
              eb deploy --profile default

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-job:
          requires:
            - build
          filters:
            branches:
              only: master
